// Generated by CoffeeScript 1.8.0

var bar, foo, baz;

baz = function() {
  debugger;
  console.log("baz");
  return bar();
};

bar = function() {
  debugger;
  console.log("bar");
  return foo();
};

foo = function() {
  debugger;
  return console.log("foo");
};
//baz()
module.exports = baz;

